#!/bin/bash

### BEGIN INIT INFO
# Provides:          gunicorn
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Python WSGI HTTP server
# Description:       Starts the Gunicorn Python WSGI HTTP server.
### END INIT INFO

NAME="gunicorn"
DESC="Python WSGI HTTP Server"

SCRIPTNAME="/etc/init.d/$NAME"

CONFIG_VARS="APP_MODULE CONFIG_FILE CONFIGS LOG_LEVEL WORKING_DIR VIRTUALENV"

PID_DIR="/var/run/$NAME"
LOG_DIR="/var/log/$NAME"


PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
. /lib/lsb/init-functions

#source /opt/CUED-web/python/engineering-calendar-python3.5/bin/activate

GUNICORN="guniorn"

if [ -f /etc/default/$NAME ]; then
  . /etc/default/$NAME
fi

USER=`whoami`
[ "$RUN_USER" ] && USER=$RUN_USER

 
if [ ! -d $PID_DIR ]; then
  mkdir $PID_DIR
  chown $USER $PID_DIR
fi

[ -x $GUNICORN ] || [ "$USE_VIRTUALENVS" = "yes" ] || log_failure_msg "Can't find $GUNICORN"

start_one()
{
  local args name pid
  name=$1
  args="--daemon --pid=$PID_DIR/$name.pid --log-file=$LOG_DIR/$name.log"

  echo "$name"
  if [ -f "$PID_DIR/$name.pid" ]; then
    pid=`cat $PID_DIR/$name.pid`

    if [ "$pid" ]; then
      ps $pid > /dev/null
      if [ $? = 0 ]; then
        echo 0 "running already"
        return 0
      else
        rm -f $PID_DIR/$name.pid
      fi
    else
      rm -f $PID_DIR/name.pid
    fi
  fi

  if [ -f $CONF_DIR/$name.conf ]; then
    . $CONF_DIR/$name.conf

    if [ -z "$APP_MODULE" ]; then
      echo 1 "no module name defined"
      return 1
    fi
    if [ -z "$CONFIG_FILE" ]; then
      echo 1 "no configuration file defined"
      return 1
    fi
    [ "$WORKING_DIR" ] && cd $WORKING_DIR
    [ "$LOG_LEVEL" ] && args="$args --log-level=$LOG_LEVEL"
    
    if  [ "$VIRTUALENV" ]; then
      . $VIRTUALENV/bin/activate 
      GUNICORN=$VIRTUALENV/bin/gunicorn
    fi
 
    if [ ! -x $GUNICORN ]; then
      echo 1 "Can't find $GUNICORN"
      return 1
    fi

    start_daemon -u $USER  "$GUNICORN $args --config=$CONFIG_FILE -- $APP_MODULE"
    echo "start_daemon -u $USER  '$GUNICORN $args --config=$CONFIG_FILE -- $APP_MODULE'"    
    # runuser -u and -c are mutually exclusive
    #/sbin/runuser -u $USER -s /bin/bash -c "$GUNICORN $args --config=$CONFIG_FILE -- $APP_MODULE"
    # echo "/sbin/runuser -u $USER -s /bin/bash -c '$GUNICORN $args --config=$CONFIG_FILE -- $APP_MODULE'"
    # sudo requires tty
    #sudo -E -u $USER $GUNICORN $args --config=$CONFIG_FILE -- $APP_MODULE
    # echo "sudo -E -u $USER $GUNICORN $args --config=$CONFIG_FILE -- $APP_MODULE"
      
    for var in $CONFIG_VARS; do
      unset $var
    done

    echo "Started server" 
  else
    echo 1 "can't find config file $CONF_DIR/$name.conf"
  fi
}

stop_one()
{
  local name pid
  name=$1

  echo "$name"
  if [ -f "$PID_DIR/$name.pid" ]; then
    pid=`cat $PID_DIR/$name.pid`

    if [ "$pid" ]; then
      ps $pid > /dev/null
      if [ $? = 0 ]; then
        kill -9 $pid
        if [ $? != 0 ]; then
          echo 1
          return 1
        fi
      fi
    fi
    rm -f $PID_DIR/$name.pid
  fi
  echo 0
}

reload_one()
{
  local name pid
  name=$1

  echo "$name"
  if [ -f "$PID_DIR/$name.pid" ]; then
    pid=`cat $PID_DIR/$name.pid`

    if [ "$pid" ]; then
      ps $pid > /dev/null
      if [ $? = 0 ]; then
        kill -HUP $pid
        if [ $? = 0 ]; then
          echo 0
        else
          echo 1
          return 1
        fi
      else
        echo 1 "not running"
        rm -f $PID_DIR/$name.pid

        return 1
      fi
    else
      echo 1 "not running"
      rm -f $PID_DIR/$name.pid

      return 1
    fi
  else
    echo 1 "not running or doesn't exists"
    return 1
  fi
}

start()
{
  if [ "x$RUN" != "xyes" ] ; then
    echo "$NAME init script disabled; edit /etc/default/$NAME"
    exit 1
  fi

  echo "Starting $DESC" "$NAME" "$CONFIGS"
  echo
  for n in ${CONFIGS[@]}; do
    start_one $n
    echo "started $n"
  done
}

stop()
{
  echo "Stopping $DESC" "$NAME"
  echo
  for n in ${CONFIGS[@]}; do
    stop_one $n
  done
}

reload()
{
  echo "Reloading $DESC" "$NAME"
  echo
  for n in ${CONFIGS[@]}; do
    reload_one $n
  done
}

restart()
{
  stop
  start
}

inc()
{
  local name pid
  name=$1

  echo "Increasing worker: "
  if [ -f "$PID_DIR/$name.pid" ]; then
    pid=`cat $PID_DIR/$name.pid`

    if [ "$pid" ]; then
      ps $pid > /dev/null
      if [ $? = 0 ]; then
        kill -TTIN $pid
        if [ $? = 0 ]; then
          echo "$name"
        else
          echo "$name"
          exit 1
        fi
      else
        echo "'$name' is not running"
        rm -f $PID_DIR/$name.pid

        exit 1
      fi
    fi
  else
    echo "'$name' is not running or doesn't exists"
    exit 1
  fi
}

dec()
{
  local name pid
  name=$1

  echo "Decreasing worker: "
  if [ -f "$PID_DIR/$name.pid" ]; then
    pid=`cat $PID_DIR/$name.pid`

    if [ "$pid" ]; then
      ps $pid > /dev/null
      if [ $? = 0 ]; then
        kill -TTOU $pid
        if [ $? = 0 ]; then
          echo "$name"
        else
          echo "$name"
          exit 1
        fi
      else
        echo "'$name' is not running"
        rm -f $PID_DIR/$name.pid

        exit 1
      fi
    fi
  else
    echo "'$name' is not running or doesn't exists"
    exit 1
  fi
}



case "$1" in
  start) start;;
  stop) stop;;
  reload) reload;;
  restart) restart;;
  start_one) start_one $2;;
  stop_one) stop_one $2;;
  reload_one) reload_one $2;;
  inc) inc $2;;
  dec) dec $2;;
  *)
    echo "Usage $0 {start|stop|reload|restart|start_one <conf>|stop_one <conf>|reload_one <conf>|inc <conf>|dec <conf>}"
    exit 1
    ;;
esac

exit 0

